apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: maas-keycloak
  namespace: sso
  labels:
    app: sso
spec:
  instances: 1
  externalAccess:
    enabled: true
  podDisruptionBudget:
    enabled: true
